In [2]:
import torch

In [3]:
#把多个张量连结（concatenate）在⼀起，把它们端对端地叠起来形成⼀个更⼤的张量
#沿行（轴-0，形状的第一个元素） 和按列（轴-1，形状的第二个元素）连结两个矩阵
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [4]:
#我们可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素：
X[-1], X[1:3]


(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [5]:
#除读取外，我们还可以通过指定索引来将元素写入矩阵。
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
#如果我们想为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。 
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])