In [2]:
import torch
#导⼊torch

In [3]:
#使⽤ arange 创建⼀个⾏向量 x。这个⾏向量包含以0开始的前12个整数，它们默认创建为整数。

x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
#以通过张量的shape属性来访问张量（沿每个轴的⻓度）的形状。
x.shape

torch.Size([12])

In [5]:
#张量中元素的总数
x.numel()

12

In [6]:
#要想改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数。要重点说明一下，虽然张量的形状发生了改变，但其元素值并没有变。 注意，通过改变张量的形状，张量的大小不会改变。
X = x.reshape(3, 4)
X
#我们可以通过-1来调用此自动计算出维度的功能。 即我们可以用x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4)。

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
#以创建⼀个形状为（2,3,4）的张量，其中所有元素都设置为0。

torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
#以创建⼀个形状为(2,3,4)的张量，其中所有元素都设置为1。
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
#码创建⼀个形状为（3,4）的张量。其中的每个元素都从均值为0、标准差为1的标准⾼斯分布（正态分布）中随机采样。
torch.randn(3, 4)


tensor([[ 1.2494, -1.3421,  0.5003, -0.5051],
        [ 0.2014,  0.1245,  0.4809, -1.1074],
        [-0.5903, -0.5705,  0.2891, -1.9202]])

In [10]:
#通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值。 在这里，最外层的列表对应于轴0，内层的列表对应于轴1。
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])